name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liQYqrn5REzaFSPY"
GITHUB_OWNER = "szliam"
GITHUB_REPO = "Nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav-3ss.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nav-3ss.pages.dev/"

